### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by Oreolek** [zorn-v/xmpp#4]
> PHP Fatal error:  Uncaught Fabiang\Xmpp\Exception\InvalidArgumentException: Argument 1 of "Fabiang\Xmpp\Exception\XMLParserException::Fabiang\Xmpp\Exception\XMLParserException::create" must be a resource returned by "xml_parser_create" in vendor/zorn-v/xmpp/src/Fabiang/Xmpp/Exception/XMLParserException.php:60

[xml_parser_create:](https://www.php.net/manual/en/function.xml-parser-create.php)

> This function returns an [XMLParser](https://www.php.net/manual/en/class.xmlparser.php) instance now; previously, a resource was returned, or false on failure.

**Comment by zorn-v** [comment]
It does not fix your actual error, but I fix exception to show correct message
Just update with `composer up`
